menubar: false
toolbar:
  - undo | redo | formatselect | fontselect | fontsizeselect | forecolor | bold italic underline | alignleft aligncenter alignright | link
plugins:
  - image
  - link
  - textcolor